services:
  pip_repository:
    image: nginx:1.27.4-alpine
    container_name: pip_repository
    hostname: pip_repository
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pip-repo:/usr/share/nginx/html:ro
    networks:
      pip_network:
        aliases:
          - pip_repository

networks:
  pip_network:
    driver: bridge